server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true

base.url: http://mockoon.tools.getontop.com:3000


uri.wallet: /wallets
uri.wallet.transactions: /transactions
uri.wallet.balance: /balance?user_id=

uri.payment: /api/v1/payments/
uri.payment.status: /status/

